export const puestos = [
  { codigo: 1, nombre: 'Abogado/a' },
  { codigo: 2, nombre: 'Auxiliar Contable' },
  { codigo: 3, nombre: 'Coordinador/a' },
  { codigo: 4, nombre: 'Coordinador/a de Área' },
  { codigo: 5, nombre: 'Coordinador/a del proyecto' },
  { codigo: 6, nombre: 'Coordinador/a General' },
  { codigo: 7, nombre: 'Comunicador/a Social' },
  { codigo: 8, nombre: 'Conserje' },
  { codigo: 9, nombre: 'Contador/a' },
  { codigo: 10, nombre: 'Contador/a' },
  { codigo: 11, nombre: 'Digitador/a' },
  { codigo: 12, nombre: 'Director/a' },
  { codigo: 13, nombre: 'Educador/a' },
  { codigo: 14, nombre: 'Educador/a' },
  { codigo: 15, nombre: 'Educador/a Juvenil' },
  { codigo: 16, nombre: 'Médico/a' },
  { codigo: 17, nombre: 'Monitoreo y Evaluación' },
  { codigo: 18, nombre: 'Piloto/a' },
  { codigo: 19, nombre: 'Procurador/a' },
  { codigo: 20, nombre: 'Psicólogo/a' },
  { codigo: 21, nombre: 'Secretario/a' },
  { codigo: 22, nombre: 'Técnico de campo' },
  { codigo: 23, nombre: 'Técnico de campo' },
  { codigo: 24, nombre: 'Trabajador/a Social' },
];
